import Link from "next/link"

export const metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of Viltreon.",
  alternates: { canonical: "/terms" },
}

/**
 * Terms of Service — based on the operator-provided draft (Alberta, Canada;
 * Alberta courts; informal resolution first; USD $100 liability floor).
 *
 * NOT legal advice. Replace every [bracketed] placeholder (legal entity name,
 * emails, address, effective date) and have a lawyer review before launch.
 */
export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 text-sm leading-relaxed">
      <header className="mb-10">
        <h1 className="text-3xl font-medium tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-muted-foreground">
          Effective date: <span className="font-mono">June 12, 2026</span>
        </p>
      </header>

      <section className="space-y-6">
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and
          use of the Viltreon website, applications, and related
          services (collectively, the &ldquo;Service&rdquo;).
        </p>
        <p>
          By creating an account, clicking to accept these Terms, or using the
          Service, you agree to be bound by these Terms. If you do not agree, do
          not use the Service.
        </p>

        <h2 className="mt-10 text-xl font-medium">1. Company information</h2>
        <p>
          Viltreon is operated from Edmonton, Alberta, Canada.
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Support: <a href="mailto:support@viltreon.com" className="underline">support@viltreon.com</a></li>
          <li>Privacy: <a href="mailto:support@viltreon.com" className="underline">support@viltreon.com</a></li>
          <li>Address: Edmonton, Alberta, Canada</li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">2. Eligibility</h2>
        <p>
          You must be at least the age of majority in your jurisdiction, or
          otherwise legally able to enter into a binding contract, to use the
          Service.
        </p>
        <p>By using the Service, you represent and warrant that:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>you have the authority to enter into these Terms;</li>
          <li>all information you provide is accurate and complete;</li>
          <li>
            you are authorized to connect any Gmail, Google, or other account
            used with the Service.
          </li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">3. Description of the Service</h2>
        <p>
          The Service helps users organize, sort, filter, classify, or manage
          Gmail messages and related account data.
        </p>
        <p>
          We may use Google APIs and other third-party services to provide the
          Service. We do not guarantee that the Service will identify, classify,
          sort, or process messages perfectly, or that results will always be
          accurate.
        </p>

        <h2 className="mt-10 text-xl font-medium">4. Account registration and security</h2>
        <p>You may need to create an account to use parts of the Service.</p>
        <p>You are responsible for:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>maintaining the confidentiality of your login credentials;</li>
          <li>all activity that occurs under your account;</li>
          <li>notifying us promptly if you suspect unauthorized access or misuse.</li>
        </ul>
        <p>
          We may suspend or secure your account if we believe it is compromised
          or at risk.
        </p>

        <h2 className="mt-10 text-xl font-medium">5. User responsibilities</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>use the Service in violation of applicable law;</li>
          <li>misuse Gmail, Google, or other connected accounts;</li>
          <li>connect an account without proper authority;</li>
          <li>attempt to interfere with, disrupt, or reverse engineer the Service;</li>
          <li>upload malicious code, spam, or harmful content;</li>
          <li>use the Service in a way that infringes another person&rsquo;s rights.</li>
        </ul>
        <p>
          You are responsible for reviewing any actions, suggestions,
          classifications, or outputs generated by the Service before relying on
          them.
        </p>

        <h2 className="mt-10 text-xl font-medium">6. Google and Gmail access</h2>
        <p>
          If you connect a Gmail or Google account, you authorize us to access
          the data necessary to provide the Service, subject to the permissions
          you grant through Google OAuth and our{" "}
          <Link href="/privacy" className="underline">Privacy Policy</Link>.
        </p>
        <p>You are responsible for ensuring that your use of the Service complies with:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Google&rsquo;s terms, policies, and developer requirements;</li>
          <li>any rules of your employer, organization, or other account owner;</li>
          <li>any legal obligations relating to the emails or data you connect.</li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">7. Customer content and data</h2>
        <p>
          You retain ownership of your content and email data, subject to the
          limited rights you grant us to operate the Service.
        </p>
        <p>
          You grant us a non-exclusive, worldwide, royalty-free license to host,
          store, process, transmit, display, and otherwise use your data only as
          needed to:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>provide and maintain the Service;</li>
          <li>support your use of the Service;</li>
          <li>secure and improve the Service;</li>
          <li>comply with law;</li>
          <li>enforce these Terms.</li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">8. Service changes and availability</h2>
        <p>
          We may modify, update, suspend, or discontinue any part of the Service
          at any time.
        </p>
        <p>
          We do not guarantee that the Service will be uninterrupted,
          error-free, or available at all times. We may perform maintenance or
          make changes that temporarily affect access.
        </p>

        <h2 className="mt-10 text-xl font-medium">9. Fees, trials, and billing</h2>
        <p>Some parts of the Service may require payment.</p>
        <p>
          Fees, billing intervals, and available plans will be shown at checkout
          or in your account. If we offer a free trial, the terms of the trial
          will be shown when you sign up. At the end of the trial, your
          subscription may convert to a paid plan unless you cancel before the
          trial ends.
        </p>
        <p>Unless required by law or expressly stated otherwise:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>fees are non-refundable;</li>
          <li>subscriptions renew automatically until canceled;</li>
          <li>you are responsible for all applicable taxes.</li>
        </ul>
        <p>
          Detailed billing terms are in our{" "}
          <Link href="/billing-terms" className="underline">Billing and Payment Terms</Link>.
        </p>

        <h2 className="mt-10 text-xl font-medium">10. Suspension and termination</h2>
        <p>We may suspend or terminate your access to the Service if:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>you violate these Terms;</li>
          <li>your payment fails;</li>
          <li>we reasonably believe your use creates a security, legal, or operational risk;</li>
          <li>required by law.</li>
        </ul>
        <p>
          You may stop using the Service at any time. You may cancel your
          subscription through your account settings or as otherwise described
          by us.
        </p>

        <h2 className="mt-10 text-xl font-medium">11. Intellectual property</h2>
        <p>
          We and our licensors own all rights in and to the Service, including
          the software, design, text, graphics, logos, trademarks, and other
          materials, except for your content and third-party materials.
        </p>
        <p>
          You may not copy, modify, distribute, sell, lease, or create
          derivative works from any part of the Service unless we give you
          written permission.
        </p>

        <h2 className="mt-10 text-xl font-medium">12. Feedback</h2>
        <p>
          If you send us suggestions, ideas, or feedback, you agree that we may
          use them without restriction or compensation to you.
        </p>

        <h2 className="mt-10 text-xl font-medium">13. Disclaimer of warranties</h2>
        <p>
          The Service is provided on an <strong>&ldquo;as is&rdquo;</strong> and{" "}
          <strong>&ldquo;as available&rdquo;</strong> basis.
        </p>
        <p>
          To the fullest extent permitted by law, we disclaim all warranties,
          express or implied, including implied warranties of merchantability,
          fitness for a particular purpose, and non-infringement.
        </p>
        <p>We do not warrant that:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>the Service will meet your needs;</li>
          <li>the Service will be uninterrupted, timely, secure, or error-free;</li>
          <li>results generated by the Service will be accurate or complete.</li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">14. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, Viltreon will
          not be liable for indirect, incidental, special, consequential,
          exemplary, or punitive damages, or for lost profits, lost revenue,
          lost data, or business interruption.
        </p>
        <p>
          To the fullest extent permitted by law, our total liability for any
          claim arising out of or relating to the Service will not exceed the
          greater of: (a) the amount you paid to us for the Service in the 12
          months before the event giving rise to the claim; or (b) USD $100,
          unless a different limit is required by law.
        </p>

        <h2 className="mt-10 text-xl font-medium">15. Indemnity</h2>
        <p>
          You agree to indemnify, defend, and hold harmless{" "}
          Viltreon from and against claims, damages, liabilities,
          losses, and expenses arising out of or related to:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>your use of the Service;</li>
          <li>your violation of these Terms;</li>
          <li>your violation of law or third-party rights;</li>
          <li>your misuse of Gmail, Google, or other connected accounts.</li>
        </ul>

        <h2 className="mt-10 text-xl font-medium">16. Governing law</h2>
        <p>
          These Terms are governed by the laws of the Province of Alberta and
          the federal laws of Canada applicable in Alberta, without regard to
          conflict of law rules.
        </p>

        <h2 className="mt-10 text-xl font-medium">17. Dispute resolution</h2>
        <p>
          Before starting formal legal action, you agree to contact us first and
          try to resolve the dispute informally.
        </p>
        <p>
          If the dispute cannot be resolved informally, it will be brought in
          the courts located in Alberta, unless applicable law requires
          otherwise. Nothing here removes a mandatory right your local
          consumer-protection law guarantees and that cannot be waived by
          contract.
        </p>

        <h2 className="mt-10 text-xl font-medium">18. Changes to these Terms</h2>
        <p>We may update these Terms from time to time.</p>
        <p>
          If we make material changes, we will provide notice by posting the
          updated Terms on our website or by other reasonable means. Your
          continued use of the Service after the updated Terms take effect means
          you accept the revised Terms.
        </p>

        <h2 className="mt-10 text-xl font-medium">19. Contact</h2>
        <p>Questions about these Terms?</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Viltreon</li>
          <li>Edmonton, Alberta, Canada</li>
          <li><a href="mailto:support@viltreon.com" className="underline">support@viltreon.com</a></li>
        </ul>

        <div className="mt-12 border-t pt-6">
          <Link href="/" className="text-muted-foreground hover:text-foreground">
            ← Back to home
          </Link>
        </div>
      </section>
    </main>
  )
}
